name: SLTBETA
favicon: null
layout_spectrum: 0.4187123463489115
typography_spectrum: 0.3410767652094364
title: Stop 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e11a21'
    - '#362981'
    - '#bab5d3'
    - '#7b72ac'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.428051559953019
  rhythmicContrast: 0.6422881160397083
purpose: []
